name: Github Action Demo
on:
  push:
    branches: [ action ]

jobs:
  Explore-GitGub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u cnux9 --password-stdin
      - name: build the image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: cnux9/scheduler:latest

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/scheduler:latest
            docker run --name scheduler-container --restart no -p 8080:8080 -e SPRING_DATASOURCE_URL="jdbc:mysql://${{ secrets.RDS_ENDPOINT }}:3306/scheduler" -e SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USERNAME }} -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }} ${{ secrets.DOCKER_USERNAME }}/scheduler:latest
            sudo docker image prune -f
